# TCJ2 Kadai Store API v0.2.0
# 基本的な設定

# Devoirsを実行して情報を更新する時刻(分)
update-times: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]
# 10分間にこのAPIにGETできる回数 (無制限なら: -1)
# (トークンごとに記録されます)
get-limit: -1

# 教科名 (インデックス数が同じ文字列が同じ教科としてリンクされます)
# 例として、ある学校学科学年の前期課程で受講する教科名を入れてあります
subjects:
  # その教科のチーム名 (Teams)
  teams:
    - "[024]J2HR2020"
    - "[024] 2020 J2A  国語"
    - "[024] 2020 J2B  国語"
    - "[024]J2_基礎数学4（2020）"
    - "J2"
    - "[024](5/8まで,2年)基礎数学4(2020)"
    - "[024](5/8まで,2年)代数幾何1(2020)"
    - "[024]物理2-2020"
    - "[024]2年理科総合(化学)2020"
    - "[024]2年歴史2(2020)"
    - "【024】English Communication3　J2AB　2020"
    - "[024]English Expression 2 (EE2)"
    - "[024]2年合同 English Communication3　2020"
    - "[024] J2電気電子工学2020"
    - "[024]J2情報工学1・PBL2(2020)"
    - "[024]J2A保健体育22020"
    - "[024]J2B保健体育22020"
    - "[024]1年2年一般基礎教育1・2(2020)"
    - "[024]2年一般基礎教育２(2020)"
  # シラバスでの教科名
  # "/"を使って教科名を区切ると、課題名と一致したほうが教科名になります
  # [例]
  # ここに書いた教科名: "りんご工学/いちご工学"
  # 課題名:            "いちご工学 第15回課題"
  # 適応される教科名:   "いちご工学"
  syllabus:
    - "HR"
    - "国語２"
    - "国語２"
    - "基礎数学４"
    - "代数・幾何１"
    - "基礎数学４"
    - "代数・幾何１"
    - "物理２"
    - "理科総合"
    - "歴史２"
    - "English Communication３"
    - "English Expression２"
    - "English Communication３"
    - "電気電子工学"
    - "情報工学1/PBL2"
    - "保健体育２"
    - "保健体育２"
    - "一般基礎教育２"
    - "一般基礎教育２"
  # 省略された教科名
  # "/"を使って教科名を区切ると、課題名と一致したほうが教科名になります
  # [例]
  # ここに書いた教科名: "りんご/いちご"
  # 課題名:            "いちご 第15回課題"
  # 適応される教科名:   "いちご"
  omitted:
    - "HR"
    - "国語"
    - "国語"
    - "基礎数"
    - "幾何"
    - "基礎数"
    - "幾何"
    - "物理"
    - "理科"
    - "歴史"
    - "EC"
    - "EE"
    - "EC"
    - "電電"
    - "情報/PBL"
    - "保体"
    - "保体"
    - "一般基礎"
    - "一般基礎"

# Discord関連の設定
discord:
  # Discordでエラー通知をするかどうか
  alarm: false
  # エラー通知をするユーザーのID (alarmをtrueにした方のみ)
  admin-id: ""
  # 通知フォーマット (alarmをtrueにした方のみ)
  #   first %s>  エラーの概要
  #   second %s> 予測される対処方法
  #   third %s>  内部のエラーメッセージ (停止メッセージ)
  message-format: "%s\n%s\n```\n%s\n```"
  # Discordボットを呼び出すコマンドの接頭辞 (alarmをtrueにした方のみ)
  command-prefix: "::kadai-store"
  # Discordボットのトークンは token.yaml のdiscord-tokenにご記入ください